//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "audit_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub trace_id: Option<String>,
    pub request_id: Option<String>,
    pub parent_id: Option<String>,
    pub span_id: Option<String>,
    pub level: String,
    pub risk_level: String,
    pub entity: String,
    pub entity_id: String,
    pub action: String,
    pub api_path: String,
    pub http_method: String,
    pub operator_id: i32,
    pub operator_name: Option<String>,
    pub operator_role: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub before: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub after: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub changed_fields: Option<Json>,
    pub ip_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub request_params: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub query_params: Option<Json>,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub http_status_code: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    pub business_id: Option<String>,
    pub batch_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub duration: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
