//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::IntentionStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "intentions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub email: String,
    pub phone: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub ip: Option<String>,
    pub country_code: Option<String>,
    pub country: Option<String>,
    pub city: Option<String>,
    pub state: Option<String>,
    pub emoji: String,
    pub source: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub referrer: Option<String>,
    pub status: IntentionStatus,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
