//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::audit_logs::Entity as AuditLogs;
pub use super::intentions::Entity as Intentions;
pub use super::login_logs::Entity as LoginLogs;
pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::sessions::Entity as Sessions;
pub use super::system_settings::Entity as SystemSettings;
pub use super::users::Entity as Users;
