//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub password: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub banned_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique)]
    pub nickname: String,
    #[sea_orm(unique)]
    pub username: String,
    pub avatar: Option<String>,
    pub role_id: Option<i32>,
    pub status: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::login_logs::Entity")]
    LoginLogs,
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::RoleId",
        to = "super::roles::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Roles,
    #[sea_orm(has_many = "super::sessions::Entity")]
    Sessions,
    #[sea_orm(has_many = "super::system_settings::Entity")]
    SystemSettings,
}

impl Related<super::login_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoginLogs.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::system_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemSettings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
